<%@ Page Language="VB" AutoEventWireup="false" CodeFile="DetailsViewIE.aspx.vb" Inherits="DetailsViewIE" %>

<html>
<head runat="server">
    <title>DetailsViewIE</title>
</head>
<body>
    <form id="form1" runat="server">
    <asp:DetailsView ID="DetailsView1" Runat="server" 
    DataSourceID='sdsAuthors'
    AutoGenerateDeleteButton=true 
    AutoGenerateEditButton=true 
    AutoGenerateInsertButton=true
    AllowPaging="True" 
    AutoGenerateRows="true" 
    DataKeyNames="au_id">
</asp:DetailsView>

<asp:SqlDataSource Runat=server ID=sdsAuthors
 ConnectionString="<%$ ConnectionStrings:pubsConn %>"
 SelectCommand="SELECT * FROM [authors]" 
 ProviderName="System.Data.SqlClient" 
 DeleteCommand="DELETE FROM [authors] WHERE [au_id] = @original_au_id" 
 InsertCommand="INSERT INTO [authors] ([au_id], [au_lname], [au_fname], 
    [phone], [address], [city], [state], [zip], [contract]) 
    VALUES (@au_id, @au_lname, @au_fname, @phone, @address, @city, 
    @state, @zip, @contract)" 
 UpdateCommand="UPDATE [authors] SET [au_lname] = @au_lname, 
    [au_fname] = @au_fname, [phone] = @phone, [address] = @address, 
    [city] = @city, [state] = @state, [zip] = @zip, 
    [contract] = @contract WHERE [au_id] = @original_au_id">
    <DeleteParameters>
        <asp:Parameter Type="String" Name="au_id"></asp:Parameter>
    </DeleteParameters>
    <UpdateParameters>
        <asp:Parameter Type="String" Name="au_lname"></asp:Parameter>
        <asp:Parameter Type="String" Name="au_fname"></asp:Parameter>
        <asp:Parameter Type="String" Name="phone"></asp:Parameter>
        <asp:Parameter Type="String" Name="address"></asp:Parameter>
        <asp:Parameter Type="String" Name="city"></asp:Parameter>
        <asp:Parameter Type="String" Name="state"></asp:Parameter>
        <asp:Parameter Type="String" Name="zip"></asp:Parameter>
        <asp:Parameter Type="Boolean" Name="contract"></asp:Parameter>
        <asp:Parameter Type="String" Name="au_id"></asp:Parameter>
    </UpdateParameters>
    <InsertParameters>
        <asp:Parameter Type="String" Name="au_id"></asp:Parameter>
        <asp:Parameter Type="String" Name="au_lname"></asp:Parameter>
        <asp:Parameter Type="String" Name="au_fname"></asp:Parameter>
        <asp:Parameter Type="String" Name="phone"></asp:Parameter>
        <asp:Parameter Type="String" Name="address"></asp:Parameter>
        <asp:Parameter Type="String" Name="city"></asp:Parameter>
        <asp:Parameter Type="String" Name="state"></asp:Parameter>
        <asp:Parameter Type="String" Name="zip"></asp:Parameter>
        <asp:Parameter Type="Boolean" Name="contract"></asp:Parameter>
    </InsertParameters>
</asp:SqlDataSource>

    </form>
</body>
</html>
